### ISSUE TITLE
 helm-charts/charts/substrate-faucet/  

### ISSUE THREAD

**Issue by radupopa2010** [paritytech/helm-charts#228]
Hello @PierreBesson  and thank you for creating this helm chart. 

I am trying to use it to deploy a faucet for Picasso Rococo 

####  Question : How would I be able to test that the deployment is good or how to use it? Using the matrix bot? 

Steps I did before installing the helm chart
1. create a matrix bot account `composablefi_faucet` 
2. create a matrix access token for the bot

Those are the values I used (removed the secrets data)
```
helm install substrate-faucet parity/substrate-faucet \
    --set faucet.secret.SMF_BACKEND_FAUCET_ACCOUNT_MNEMONIC="removed" \
    --set faucet.secret.SMF_BOT_MATRIX_ACCESS_TOKEN="removed" \
    --set faucet.config.SMF_BACKEND_RPC_ENDPOINT="https://picasso-rococo-rpc-lb.composablenodes.tech/" \
    --set faucet.config.SMF_BACKEND_INJECTED_TYPES='{}' \
    --set faucet.config.SMF_BACKEND_NETWORK_DECIMALS='12' \
    --set faucet.config.SMF_BOT_MATRIX_SERVER="https://matrix.org" \
    --set faucet.config.SMF_BOT_MATRIX_BOT_USER_ID="@composablefi_faucet:matrix.org" \
    --set faucet.config.SMF_BOT_NETWORK_UNIT="PICA" \
    --set faucet.config.SMF_BOT_DRIP_AMOUNT="1"
```

Testing the endpoint   picasso-rpc-lb.composablenodes.tech  seems to be fine
```
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "rpc_methods"}'  https://westend-rpc.polkadot.io
{"jsonrpc":"2.0","result":{"methods":["account_nextIndex","author_hasKey","author_hasSessionKeys","author_insertKey
... (content removed)


echo '{"id":1, "jsonrpc":"2.0", "method": "rpc_methods"}' | websocat wss://picasso-rpc-lb.composablenodes.tech
{"jsonrpc":"2.0","result":{"methods":["account_nextIndex","assets_balanceOf","assets_listAssets","author_hasKey","author_hasSessionKeys","author_insertKey","author_pendingExtrinsics","author_removeExtrinsic","author_rotateKeys","author_submitAndWatchExtrinsic","author_sub
...  (content removed)

```

By the way `https://rococo-rpc.polkadot.io` seems to be down
```
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "rpc_methods"}'  https://rococo-rpc.polkadot.io
Service Unavailable

echo '{"id":1, "jsonrpc":"2.0", "method": "rpc_methods"}' | websocat wss://rococo-rpc.polkadot.io
websocat: WebSocketError: WebSocketError: Received unexpected status code (503 Service Unavailable)
websocat: error running
```

while `https://westend-rpc.polkadot.io/`  works 

```
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "rpc_methods"}'  https://westend-rpc.polkadot.io
{"jsonrpc":"2.0","result":{"methods":["account_nextIndex","author_hasKey","author_hasSessionKeys","author_insertKey","author_pendingExtrinsics","author_removeExtrinsic","author_rotateKeys","author_submitAndWatchExtrinsic","author_submitExtrinsic","author_unwatchExtrinsi
... (content removed)

echo '{"id":1, "jsonrpc":"2.0", "method": "rpc_methods"}' | websocat wss://westend-rpc.polkadot.io
{"jsonrpc":"2.0","result":{"methods":["account_nextIndex","author_hasKey","author_hasSessionKeys","author_insertKey
... (content removed)
```

Here is what I have in the logs

<details open>
<summary>kubectl logs substrate-faucet-85b7c64b7f-vcqsn  (expand me)  </summary>

```
kubectl logs substrate-faucet-85b7c64b7f-vcqsn 
yarn run v1.22.5
$ node ./build/src/start.js
2023-03-30 12:46:26        API/INIT: Api will be available in a limited mode since the provider does not support subscriptions
[2023-03-30T12:46:26.928] [INFO] default - 🚰 Plip plop - Creating the faucets's account
[2023-03-30T12:46:26.929] [INFO] default - Ignore list: (1 entries)
[2023-03-30T12:46:26.929] [INFO] default -  ''
SMF:
  📦 BOT:
     ✅ BACKEND_URL: "http://localhost:5555"
     ✅ DRIP_AMOUNT: 1
     ✅ MATRIX_ACCESS_TOKEN: *****
     ✅ MATRIX_BOT_USER_ID: "@composablefi_faucet:matrix.org"
     ✅ MATRIX_SERVER: "https://matrix.org"
     ✅ NETWORK_DECIMALS: 12
     ✅ NETWORK_UNIT: "PICA"
     ✅ FAUCET_IGNORE_LIST: ""
     ✅ DEPLOYED_REF: "unset"
     ✅ DEPLOYED_TIME: "unset"
[2023-03-30T12:46:26.965] [INFO] default - ✅ BOT config validated
SMF:
  📦 BACKEND:
     ✅ FAUCET_ACCOUNT_MNEMONIC: *****
     ✅ FAUCET_BALANCE_CAP: 100
     ✅ INJECTED_TYPES: "[]"
     ✅ NETWORK_DECIMALS: 12
     ✅ PORT: 5555
     ✅ RPC_ENDPOINT: "https://picasso-rococo-rpc-lb.composablenodes.tech/"
     ✅ DEPLOYED_REF: "paritytech/faucet:latest"
     ✅ DEPLOYED_TIME: "2023-03-30T15:45:28"
     ✅ EXTERNAL_ACCESS: false
     ✅ DRIP_AMOUNT: "0.5"
     ✅ RECAPTCHA_SECRET: *****
[2023-03-30T12:46:26.979] [INFO] default - ✅ BACKEND config validated
[2023-03-30T12:46:26.995] [INFO] default - Starting faucet v1.1.2
[2023-03-30T12:46:26.995] [INFO] default - Faucet backend listening on port 5555.
[2023-03-30T12:46:26.995] [INFO] default - Using @polkadot/api 10.0.1
Connected to the in-memory SQlite database.
Getting saved sync token...
Getting push rules...
Attempting to send queued to-device messages
Got saved sync token
Got reply from saved sync, exists? false
All queued to-device messages sent
2023-03-30 12:46:31        API/INIT: RPC methods not decorated: assets_balanceOf, assets_listAssets, crowdloanRewards_amountAvailableToClaimFor, ibc_clientUpdateTimeAndHeight, ibc_generateConnectionHandshakeProof, ibc_queryBalanceWithAddress, ibc_queryChannel, ibc_queryChannelClient, ibc_queryChannels, ibc_queryClientConsensusState, ibc_queryClientState, ibc_queryClients, ibc_queryConnection, ibc_queryConnectionChannels, ibc_queryConnectionUsingClient, ibc_queryConnections, ibc_queryDenomTrace, ibc_queryDenomTraces, ibc_queryEvents, ibc_queryLatestHeight, ibc_queryNewlyCreatedClient, ibc_queryNextSeqRecv, ibc_queryPacketAcknowledgement, ibc_queryPacketAcknowledgements, ibc_queryPacketCommitment, ibc_queryPacketCommitments, ibc_queryPacketReceipt, ibc_queryProof, ibc_queryRecvPackets, ibc_querySendPackets, ibc_queryUnreceivedAcknowledgement, ibc_queryUnreceivedPackets, ibc_queryUpgradedClient, ibc_queryUpgradedConnectionState, pablo_pricesFor, pablo_simulateAddLiquidity, pablo_simulateRemoveLiquidity
2023-03-30 12:46:32        API/INIT: picasso/10011: Not decorating unknown runtime apis: 0x9c53906fa888fe7c/1, 0x5c497be959ff24ab/1, 0xf60c4a6e7ca253cc/1, 0xa74824145d05c12a/1
Got push rules
Adding default global override for .org.matrix.msc3786.rule.room.server_acl
Checking lazy load status...
Checking whether lazy loading has changed in store...
Storing client options...
Stored client options
Getting filter...
[2023-03-30T12:46:36.615] [INFO] default - Fetched faucet balance 💰
Sending initial sync request...
Waiting for saved sync before starting sync processing...
Adding default global override for .org.matrix.msc3786.rule.room.server_acl
Caught /sync error TypeError: Cannot read properties of undefined (reading 'cryptoStore')
    at /faucet/node_modules/matrix-js-sdk/lib/sync.js:1191:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.promiseMapSeries (/faucet/node_modules/matrix-js-sdk/lib/utils.js:445:5)
    at async SyncApi.processSyncResponse (/faucet/node_modules/matrix-js-sdk/lib/sync.js:1184:5)
    at async SyncApi.doSync (/faucet/node_modules/matrix-js-sdk/lib/sync.js:843:9)
[2023-03-30T13:03:00.027] [INFO] default - Auto-joined !JTMeQUcNDfTSdeIIvP:matrix.org.
EventTimelineSet.addLiveEvent: ignoring duplicate event $yZzI-R0yRHKSxnsfHpGveuj3QMgs7T3Zugk7NB__mmI
[2023-03-30T13:03:06.314] [INFO] default - Auto-joined !JTMeQUcNDfTSdeIIvP:matrix.org.
2023-03-30 20:41:56        RPC-CORE: queryStorageAt(keys: Vec<StorageKey>, at?: BlockHash): Vec<StorageChangeSet>:: [502]: Bad Gateway
[2023-03-30T20:41:56.989] [ERROR] default - Error: [502]: Bad Gateway
    at HttpProvider._HttpProvider_send (/faucet/node_modules/@polkadot/rpc-provider/cjs/http/index.js:162:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async callWithRegistry (/faucet/node_modules/@polkadot/rpc-core/cjs/bundle.js:172:28)
2023-03-30 20:44:06        RPC-CORE: queryStorageAt(keys: Vec<StorageKey>, at?: BlockHash): Vec<StorageChangeSet>:: [502]: Bad Gateway
[2023-03-30T20:44:06.311] [ERROR] default - Error: [502]: Bad Gateway
    at HttpProvider._HttpProvider_send (/faucet/node_modules/@polkadot/rpc-provider/cjs/http/index.js:162:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async callWithRegistry (/faucet/node_modules/@polkadot/rpc-core/cjs/bundle.js:172:28)

```
</details>

**Comment by radupopa2010** [comment]
fond the way to use the faucet and created a PR 
https://github.com/paritytech/helm-charts/pull/230
